// Generated by Haxe 3.4.4
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var base_Main = function() {
	nanofl.MovieClip.call(this,nanofl.Player.library.getItem("scene"));
};
base_Main.__super__ = nanofl.MovieClip;
base_Main.prototype = $extend(nanofl.MovieClip.prototype,{
});
var Main = function() {
	base_Main.call(this);
};
Main.__super__ = base_Main;
Main.prototype = $extend(base_Main.prototype,{
	init: function() {
	}
	,onEnterFrame: function() {
	}
	,onMouseDown: function(e) {
	}
});
createjs.DisplayObject.prototype.setBounds = function(x, y, width, height) { this._bounds = x != null ? (this._bounds || new createjs.Rectangle()).setValues(x, y, width, height) : null; };
